services:
  users:
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - seq
  tweets:
    build:
      context: .
      dockerfile: TweetService/Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - seq
      - users
  seq:
    image: datalust/seq
    ports:
    - 5341:5341
    - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
volumes:
  rps_seq_data:
