services:
  users:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - seq
    networks:
      - microservices_net
  tweets:
    build:
      context: .
      dockerfile: TweetService/Dockerfile
    environment:
      - EASYNETQ_CONNECTION_STRING=host=rabbitmq;port=5672;virtualHost=/;username=guest;password=guest
    ports:
      - 8081:8080
    depends_on:
      - seq
      - users
    networks:
      - microservices_net
  seq:
    image: datalust/seq
    ports:
    - 5341:5341
    - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
      - microservices_net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 15672:15672
    networks:
      - microservices_net
volumes:
  rps_seq_data:
networks:
  microservices_net: