apiVersion: v1
kind: Service
metadata:
  name: tweetservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: gatewayservice
  ports:
    - port: 8080
      nodePort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  name: gatewayservice
  namespace: default
  labels:
    app: tweetservice
spec:
  containers:
    - name: gatewayservice
      image: larsvegascph/gatewayservice
      imagePullPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: tweetservice
  namespace: default
  labels:
    app: tweetservice
spec:
  containers:
    - name: tweetservice
      image: larsvegascph/tweetservice
      imagePullPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: userservice
  namespace: default
  labels:
    app: tweetservice
spec:
  containers:
    - name: userservice
      image: larsvegascph/userservice
      imagePullPolicy: Never